[package]
name = "roc_host"
version = "0.0.1"
edition = "2021"

[lib]
name = "host"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
rustls = "0.23.45"
rustls-pki-types = { version = "1.15.1", features = ["std"] }
webpki-roots = "1.0.9"

[profile.release]
lto = true
strip = "debuginfo"
panic = "abort"
