[package]
name = "roc_host"
version = "0.2.1"
edition = "2021"

[lib]
name = "host"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
corosensei = "0.3.4"
libc = "0.2.189"
mio = { version = "1.2.3", features = ["os-poll", "net", "os-ext"] }
rustls = "0.23.45"
rustls-pki-types = { version = "1.15.1", features = ["std"] }
slab = "0.4.12"
webpki-roots = "1.0.9"

[profile.release]
lto = true
strip = "debuginfo"
panic = "abort"
