app [main!] { roc: "nightly-2026-09-24-f45bfbe", pf: platform "../../platform/main.roc" }

import pf.Cryptography as C
import pf.Noise
import pf.Stdout
import Vectors

# Runs `Noise` against the cacophony test vectors (Vectors.roc, generated by
# scripts/gen_noise_vectors.py): for each, both sides of the handshake with
# the vector's keys and fixed ephemeral keys, checking every message's
# ciphertext and payload, the handshake hash, and the transport messages
# after it.

main! : List(Str) => Try({}, _)
main! = |_| {
	var $failed = 0
	for vector in Vectors.all {
		match run!(vector) {
			Ok({}) => {}
			Err(err) => {
				$failed = $failed + 1
				Stdout.line!("FAIL  noise: ${vector.name}: ${Str.inspect(err)}")?
			}
		}
	}
	count = List.len(Vectors.all)
	if $failed == 0 {
		Stdout.line!("All ${count.to_str()} Noise test vectors passed")
	} else {
		Stdout.line!("${$failed.to_str()} of ${count.to_str()} Noise test vectors failed")?
		Err(Exit(1))
	}
}

## Bytes from hex.
hex = |text| {
	digit = |c| if c >= 97 c - 87 else if c >= 65 c - 55 else c - 48
	digits = Str.to_utf8(text)
	var $out = []
	var $i = 0
	while $i + 1 < List.len(digits) {
		$out = List.append($out, digit(List.get(digits, $i) ?? 48) * 16 + digit(List.get(digits, $i + 1) ?? 48))
		$i = $i + 2
	}
	$out
}

## One side's configuration, from the vector's keys for it.
side_config = |vector, role| {
	keys =
		match role {
			Initiator => { prologue: vector.init_prologue, static_key: vector.init_static, ephemeral: vector.init_ephemeral, remote_static: vector.init_remote_static, psks: vector.init_psks }
			Responder => { prologue: vector.resp_prologue, static_key: vector.resp_static, ephemeral: vector.resp_ephemeral, remote_static: vector.resp_remote_static, psks: vector.resp_psks }
		}
	var $config = Noise.config(vector.pattern, role).with_cipher(vector.cipher).with_prologue(hex(keys.prologue))
	if !Str.is_empty(keys.static_key) {
		$config = $config.with_static_key(C.X25519.secret_key_from_bytes(hex(keys.static_key))?)
	}
	if !Str.is_empty(keys.remote_static) {
		$config = $config.with_remote_static_key(C.X25519.public_key_from_bytes(hex(keys.remote_static))?)
	}
	if !Str.is_empty(keys.ephemeral) {
		$config = $config.with_fixed_ephemeral_key_for_testing(C.X25519.secret_key_from_bytes(hex(keys.ephemeral))?)
	}
	for (position, psk) in List.map2(vector.psk_positions, keys.psks, |position, psk| (position, psk)) {
		$config = $config.with_psk(position, hex(psk))
	}
	Ok($config)
}

check = |ok, err| if ok Ok({}) else Err(err)

run! = |vector| {
	one_way = List.contains([N, K, X], vector.pattern)
	var $initiator = Noise.start!(side_config(vector, Initiator)?)?
	var $responder = Noise.start!(side_config(vector, Responder)?)?
	var $index = 0
	# The handshake.
	while !$initiator.is_finished() {
		message = List.get(vector.messages, $index) ?? { payload: "", ciphertext: "" }
		payload = hex(message.payload)
		if one_way or $index % 2 == 0 {
			(sent, initiator) = $initiator.write_message!(payload)?
			check(sent == hex(message.ciphertext), Ciphertext($index))?
			(received, responder) = $responder.read_message!(sent)?
			check(received == payload, Payload($index))?
			$initiator = initiator
			$responder = responder
		} else {
			(sent, responder) = $responder.write_message!(payload)?
			check(sent == hex(message.ciphertext), Ciphertext($index))?
			(received, initiator) = $initiator.read_message!(sent)?
			check(received == payload, Payload($index))?
			$initiator = initiator
			$responder = responder
		}
		$index = $index + 1
	}
	check($responder.is_finished(), ResponderNotFinished)?
	i = $initiator.finish()?
	r = $responder.finish()?
	check(i.handshake_hash == hex(vector.handshake_hash) and r.handshake_hash == i.handshake_hash, HandshakeHash)?
	# Transport messages, with the split cipher states.
	var $i_send = i.send
	var $i_receive = i.receive
	var $r_send = r.send
	var $r_receive = r.receive
	while $index < List.len(vector.messages) {
		message = List.get(vector.messages, $index) ?? { payload: "", ciphertext: "" }
		payload = hex(message.payload)
		if one_way or $index % 2 == 0 {
			(sent, send) = $i_send.encrypt!([], payload)?
			check(sent == hex(message.ciphertext), Ciphertext($index))?
			(received, receive) = $r_receive.decrypt!([], sent)?
			check(received == payload, Payload($index))?
			$i_send = send
			$r_receive = receive
		} else {
			(sent, send) = $r_send.encrypt!([], payload)?
			check(sent == hex(message.ciphertext), Ciphertext($index))?
			(received, receive) = $i_receive.decrypt!([], sent)?
			check(received == payload, Payload($index))?
			$r_send = send
			$i_receive = receive
		}
		$index = $index + 1
	}
	Ok({})
}
