#!/usr/bin/env python3
"""Generate tests/noise/Vectors.roc from the cacophony Noise test vectors.

Usage:
    curl -fsSLO https://raw.githubusercontent.com/mcginty/snow/main/tests/vectors/cacophony.txt
    python3 scripts/gen_noise_vectors.py cacophony.txt > tests/noise/Vectors.roc

Only the vectors for what `Noise` implements are kept: the fundamental
patterns (with any psk modifiers) over 25519, ChaChaPoly or AESGCM, and
SHA256. The output is committed, so the tests don't need the network.
"""

import json
import re
import sys

PATTERN = re.compile(
    r"^Noise_(N|K|X|NN|NK|NX|KN|KK|KX|XN|XK|XX|IN|IK|IX)((?:psk\d)(?:\+psk\d)*)?_25519_(ChaChaPoly|AESGCM)_SHA256$"
)


def roc_str(s):
    return '"' + s + '"'


def main(path):
    vectors = json.load(open(path))["vectors"]
    out = []
    out.append("# Generated by scripts/gen_noise_vectors.py from the cacophony test vectors")
    out.append("# (https://github.com/haskell-cryptography/cacophony, as copied in the snow")
    out.append("# crate's tests/vectors/cacophony.txt). Don't edit by hand.")
    out.append("Vectors := [].{")
    out.append("")
    out.append("\tall : List(Vector)")
    out.append("\tall = [")
    count = 0
    for v in vectors:
        m = PATTERN.match(v["protocol_name"])
        if not m:
            continue
        count += 1
        pattern, psks, cipher = m.group(1), m.group(2) or "", m.group(3)
        positions = [int(p) for p in re.findall(r"psk(\d)", psks)]
        messages = ", ".join(
            "{ payload: %s, ciphertext: %s }" % (roc_str(msg["payload"]), roc_str(msg["ciphertext"]))
            for msg in v["messages"]
        )
        fields = [
            ("name", roc_str(v["protocol_name"])),
            ("pattern", pattern),
            ("cipher", "ChaChaPoly" if cipher == "ChaChaPoly" else "AesGcm"),
            ("psk_positions", "[" + ", ".join(str(p) for p in positions) + "]"),
            ("init_prologue", roc_str(v.get("init_prologue", ""))),
            ("init_static", roc_str(v.get("init_static", ""))),
            ("init_ephemeral", roc_str(v.get("init_ephemeral", ""))),
            ("init_remote_static", roc_str(v.get("init_remote_static", ""))),
            ("init_psks", "[" + ", ".join(roc_str(p) for p in v.get("init_psks", [])) + "]"),
            ("resp_prologue", roc_str(v.get("resp_prologue", ""))),
            ("resp_static", roc_str(v.get("resp_static", ""))),
            ("resp_ephemeral", roc_str(v.get("resp_ephemeral", ""))),
            ("resp_remote_static", roc_str(v.get("resp_remote_static", ""))),
            ("resp_psks", "[" + ", ".join(roc_str(p) for p in v.get("resp_psks", [])) + "]"),
            ("handshake_hash", roc_str(v.get("handshake_hash", ""))),
            ("messages", "[" + messages + "]"),
        ]
        out.append("\t\t{ " + ", ".join("%s: %s" % f for f in fields) + " },")
    out.append("\t]")
    out.append("")
    out.append("\t## One test vector: both sides' keys (hex; empty if the pattern has")
    out.append("\t## none), the messages in order (from the initiator first, alternating;")
    out.append("\t## the handshake's, then transport messages), and the handshake hash.")
    out.append(
        "\tVector : { name : Str, pattern : [N, K, X, NN, NK, NX, KN, KK, KX, XN, XK, XX, IN, IK, IX], "
        "cipher : [ChaChaPoly, AesGcm], psk_positions : List(U64), init_prologue : Str, init_static : Str, "
        "init_ephemeral : Str, init_remote_static : Str, init_psks : List(Str), resp_prologue : Str, "
        "resp_static : Str, resp_ephemeral : Str, resp_remote_static : Str, resp_psks : List(Str), "
        "handshake_hash : Str, messages : List({ payload : Str, ciphertext : Str }) }"
    )
    out.append("}")
    print("\n".join(out))
    print(f"{count} vectors", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1])
