#!/usr/bin/env python3
"""Write the license notices for the Rust code compiled into the host library.

    scripts/rust_notices.py            # (re)write platform/licenses/
    scripts/rust_notices.py --check    # fail if they're out of date

Every crate linked into libhost.a for a release target (build-time-only
crates such as `cc` don't end up in it) gets its name, version, license
expression and the full text of every license file it ships. AWS-LC's C code
(inside aws-lc-sys) carries its own combined notice, which is included too.
The Rust standard library, also linked in, is covered by its own
COPYRIGHT-library file from the toolchain, copied alongside.

Run it after changing dependencies (`just licenses`); CI checks it's current.
"""

import json
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "platform" / "licenses"
OUT = OUT_DIR / "rust-host.txt"
STD_COPYRIGHT = "rust-std-COPYRIGHT.html"

# The targets a release bundle has hosts for.
TARGETS = [
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
]

LICENSE_PREFIXES = ("license", "licence", "copying", "notice")

# Extra notice files inside a crate, beyond its top-level license files.
EXTRA_FILES = {"aws-lc-sys": ["aws-lc/LICENSE"]}


def run(*args):
    return subprocess.run(args, cwd=ROOT, check=True, capture_output=True, text=True).stdout


def linked_crates():
    """(name, version) of every crate in the host's normal dependency tree."""
    crates = set()
    for target in TARGETS:
        out = run("cargo", "tree", "-e", "normal", "--target", target, "--prefix", "none", "-f", "{p}")
        for line in out.splitlines():
            parts = line.split()
            if len(parts) >= 2 and parts[0] != "roc_host":
                crates.add((parts[0], parts[1].lstrip("v")))
    return crates


def render():
    metadata = json.loads(run("cargo", "metadata", "--format-version", "1", "--locked"))
    packages = {(p["name"], p["version"]): p for p in metadata["packages"]}
    sections = [
        "Third-party notices for the Rust code in roc-net's host library (libhost.a)\n"
        "==========================================================================\n\n"
        "Generated by scripts/rust_notices.py from Cargo.lock; do not edit.\n\n"
        "The Rust standard library, also linked in, is licensed MIT OR Apache-2.0;\n"
        f"its notices, including code it bundles, are in {STD_COPYRIGHT}.\n",
    ]
    for name, version in sorted(linked_crates()):
        package = packages[(name, version)]
        source = pathlib.Path(package["manifest_path"]).parent
        header = f"{name} {version}\nLicense: {package.get('license') or 'see below'}"
        if package.get("repository"):
            header += f"\nSource: {package['repository']}"
        texts = []
        files = sorted(f for f in source.iterdir() if f.is_file() and f.name.lower().startswith(LICENSE_PREFIXES))
        files += [source / extra for extra in EXTRA_FILES.get(name, [])]
        for path in files:
            texts.append(f"--- {path.relative_to(source)} ---\n\n{path.read_text(errors='replace').strip()}\n")
        if not texts:
            sys.exit(f"{name} {version} ships no license file; add its notice by hand")
        sections.append("=" * 78 + "\n" + header + "\n" + "=" * 78 + "\n\n" + "\n".join(texts))
    return "\n\n".join(sections)


def std_copyright():
    sysroot = pathlib.Path(run("rustc", "--print", "sysroot").strip())
    return sysroot / "share" / "doc" / "rust" / "COPYRIGHT-library.html"


def main():
    text = render()
    std = std_copyright()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text or not (OUT_DIR / STD_COPYRIGHT).exists():
            sys.exit("platform/licenses/ is out of date: run `just licenses` and commit the result")
        print("platform/licenses/ is up to date")
        return
    OUT_DIR.mkdir(exist_ok=True)
    OUT.write_text(text)
    shutil.copyfile(std, OUT_DIR / STD_COPYRIGHT)
    print(f"wrote {OUT.relative_to(ROOT)} and {STD_COPYRIGHT}")


if __name__ == "__main__":
    main()
